;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Interact",DevComment="")
+GameplayTagList=(Tag="Cooldown.AoeAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Shield",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Equipment.HandUsage.EitherHand",DevComment="")
+GameplayTagList=(Tag="Equipment.HandUsage.MainHand",DevComment="")
+GameplayTagList=(Tag="Equipment.HandUsage.OffHand",DevComment="")
+GameplayTagList=(Tag="Equipment.HandUsage.TwoHanded",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.WeaponSet.1.MainHand",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.WeaponSet.1.OffHand",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.WeaponSet.2.MainHand",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.WeaponSet.2.OffHand",DevComment="")
+GameplayTagList=(Tag="Equipment.Trait.DualWield",DevComment="")
+GameplayTagList=(Tag="Equipment.Trait.Shield",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Dash",DevComment="")
+GameplayTagList=(Tag="Event.ActivateAbility.Equip",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Input",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AOEAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.FillShield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.AxeSwing",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Combo",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AoeIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Heal.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.LightningBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn.GreenFire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldBubble",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldDown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShieldUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.TargetingCamera",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.1",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.2",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.Interact",DevComment="")
+GameplayTagList=(Tag="InputTag.WeaponSet.1",DevComment="")
+GameplayTagList=(Tag="InputTag.WeaponSet.2",DevComment="")
+GameplayTagList=(Tag="Inventory.Item.1",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="UI.Action.Character",DevComment="")
+GameplayTagList=(Tag="UI.Action.Crafting",DevComment="")
+GameplayTagList=(Tag="UI.Action.Inventory",DevComment="")
+GameplayTagList=(Tag="UI.Action.Journal",DevComment="")
+GameplayTagList=(Tag="UI.Action.Map",DevComment="")
+GameplayTagList=(Tag="UI.Action.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Action.Skills",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Bow",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Dagger",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Shield",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Sword",DevComment="")
+GameplayTagList=(Tag="Weapon.Family.Wand",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Staff",DevComment="")

